sensors:
  ouster:
    type: 'oakd'
    msg_type: 'depthai_ros_msgs/SpatialDetectionArray'
    topic: '/yolov4_publisher/color/yolov4_Spatial_detections'

tracker:
  my_graph_tracker:
    type: 'graph_tracker'
    det_topic: '/detections_3d'
    frame: 'base_link'

detectors:
  oakd_sensor:
    type: 'oakd'
    topic: '/yolov4_publisher/color/yolov4_Spatial_detections'  
    msg_type: 'SpatialDetectionArray'
    conf_thresh: 0.
    hfov: 69
    vfov: 55
    img_height: 416
    img_width: 416
    cat_labels: ["person", "bicycle", "car", "motorbike", "aeroplane",
            "bus",
            "train",
            "truck",
            "boat",
            "traffic light",
            "fire hydrant",
            "stop sign",
            "parking meter",
            "bench",
            "bird",
            "cat",
            "dog",
            "horse",
            "sheep",
            "cow",
            "elephant",
            "bear",
            "zebra",
            "giraffe",
            "backpack",
            "umbrella",
            "handbag",
            "tie",
            "suitcase",
            "frisbee",
            "skis",
            "snowboard",
            "sports ball",
            "kite",
            "baseball bat",
            "baseball glove",
            "skateboard",
            "surfboard",
            "tennis racket",
            "bottle",
            "wine glass",
            "cup",
            "fork",
            "knife",
            "spoon",
            "bowl",
            "banana",
            "apple",
            "sandwich",
            "orange",
            "broccoli",
            "carrot",
            "hot dog",
            "pizza",
            "donut",
            "cake",
            "chair",
            "sofa",
            "pottedplant",
            "bed",
            "diningtable",
            "toilet",
            "tvmonitor",
            "laptop",
            "mouse",
            "remote",
            "keyboard",
            "cell phone",
            "microwave",
            "oven",
            "toaster",
            "sink",
            "refrigerator",
            "book",
            "clock",
            "vase",
            "scissors",
            "teddy bear",
            "hair drier",
            "toothbrush"
        ]
