sensors:
  ouster:
    type: 3d_lidar
    msg_type: 'sensor_msgs/PointCloud2'
    topic: '/philbart/lidar_points'

detectors:
  coda_pcdet:
    type: 'pcdet'
    topic: '/philbart/lidar_points'
    msg_type: 'PointCloud2'
    config: 'models/pvrcnn_oracle_allclass.yaml'
    checkpoint: 'models/coda128_allclass_bestoracle.pth'
    # conf_thresh: 0.5
    # cat_labels: ['Car', 'Pedestrian', 'Cyclist']
