sensors:
  ouster:
    type: 3d_lidar
    msg_type: 'sensor_msgs/PointCloud2'
    topic: '/philbart/lidar_points'

detectors:
  kitti_pointpillars:
    type: 'mmdet3d'
    topic: '/philbart/lidar_points'  
    msg_type: 'PointCloud2'
    config: 'models/fcaf3d_2xb8_sunrgbd-3d-10class.py'
    checkpoint: 'models/fcaf3d_8x2_sunrgbd-3d-10class_20220805_165017.pth'
    conf_thresh: 0.5
    cat_labels: ['Car', 'Pedestrian', 'Cyclist']
